// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['profile']['ProfileModule']['Greet'](arg1);
}

export function Shoutdown(arg1) {
  return window['go']['profile']['ProfileModule']['Shoutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['profile']['ProfileModule']['Start'](arg1);
}
