// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMenusName() {
  return window['go']['controller']['MenuModuleController']['GetMenusName']();
}
