// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMenusName() {
  return window['go']['menu']['MenuModule']['GetMenusName']();
}

export function Shoutdown(arg1) {
  return window['go']['menu']['MenuModule']['Shoutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['menu']['MenuModule']['Start'](arg1);
}
