// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetMenusName():Promise<Array<string>>;

export function Shoutdown(arg1:context.Context):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;
